name: Test Storybook Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'test.*'

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug info
        run: |
          echo "ref: ${{ github.ref }}"
          echo "sha: ${{ github.sha }}"
          echo "event: ${{ github.event_name }}"

  deploy-storybook:
    needs: debug
    uses: ./.github/workflows/storybook.yml
    with:
      ref: ${{ github.ref }}
